import { strings as plStrings } from "../pl/strings";

export const strings: typeof plStrings & any = {
  "intl.switch.english": "Switch to english 🇬🇧",
  "intl.switch.polish": "Przełącz na język polski 🇵🇱",

  "virtual-university": "Virtual University",
  student: "Student",
  teacher: "Dydaktyk",
  login: "Login",
  "login.id": "Student ID",
  "login.password": "Password",
  "login.logIn": "Sign in",
  "login.forgot": "I forgot password",

  "login.button": "Sign in",

  "grade.grade": "Grade",
  "grade.teacher": "Teacher",
  "grade.lessonType": "Lesson type",
  "grade.lessonType.aud": "Auditorium",
  "grade.lessonType.labs": "Laboratory",
  "grade.lessonType.proj": "Project",
  "grade.lessonType.lectures": "Lecture",
  "grade.group": "Group",
  "grade.term": "Date",
  "grade.type": "Subject type",
  "grade.type.p": "Mandatory",
  "grade.type.r": "Differences",
  "grade.type.e": "Optional",
  "grade.length": "Hours",
  "grade.ects": "ECTS",
  "grade.finalGrade": "Final grade",
  "grade.finalGrade.empty": "No final grade",
  "grade.seePartials": "See partial grades",
  "grade.partials": "Partial grades",
  "grade.partials.empty": "No partial grades",

  "gradePage.accumulatedEcts": "Accumulated ECTS",
  "gradePage.avgPerYear": "Year GPA",
  "gradePage.avgPerSemester": "Semester GPA",
  "gradePage.summary": "Summary",
  "gradePage.subjects": "Subjects",

  "nav.university": "Your university",
  "nav.calendar": "Calendar",
  "nav.profile": "Profile",
  "nav.logout": "Log out",
  "nav.news": "Announcements",
  "nav.contact": "Contact",
  "nav.university.grades": "Subjects",

  "contact.deansOffice": "Dean's office",
  "contact.deansOffice.description":
    "Electrical Engineering, Automatics, Computer Science and Biomedical Engineering",
  "contact.support": "Tech support",
  "contact.support.description": "Virtual University issues",

  "see.news": "See more announcements",
  "see.deansOffice": "Go to dean's office page",
  "see.vu": "Go to CRI page",
  change: "Change",
  "change.password": "Change password",

  "news.noNeews": "No announcements",

  "calendar.see": "See calendar",

  "profile.personalData": "Personal information",
  "profile.financialData": "Financial information",
  "profile.loginData": "Account information",
  "profile.agreements": "Agreements",
  "profile.id": "Student ID",
  "profile.phone": "Phone",
  "profile.email": "Email",
  "profile.address": "Address",
  "profile.postAddress": "Correspondence address",
  "profile.bornPlace": "Place of birth",
  "profile.bornTime": "Date of birth",
  "profile.motherName": "Mother's name",
  "profile.fatherName": "Father's name",
  "profile.pesel": "PESEL",
  "profile.nationalId": "ID",
  "profile.accountNumber": "Account number",
  "profile.agreement.email": "I agree to share my e-mail",
  "profile.agreement.parents": "I agree to inform my parents",
  "profile.info":
    "Students shall be required to inform the Dean immediately about any changes regarding their marital status, name or address, as well as about changes regarding their financial conditions, if they influence granting financial support as well as its amount.",
};
