export const strings = {
  "virtual-university": "Writualny Dziekanat",
  student: "Student",
  teacher: "Dydaktyk",
  login: "Logowanie",
  "login.id": "Identyfikator",
  "login.password": "Hasło",
  "login.logIn": "Zaloguj",
  "login.forgot": "Zapomniałem hasła",

  "login.button": "Zaloguj",

  "grade.grade": "Ocena",
  "grade.teacher": "Prowadzący",
  "grade.lessonType": "Forma zajęć",
  "grade.lessonType.aud": "Ćwiczenia audytoryjne",
  "grade.lessonType.labs": "Ćwiczenia laboratoryjne",
  "grade.lessonType.proj": "Ćwiczenia projektowe",
  "grade.lessonType.lectures": "Wykład",
  "grade.group": "Grupa",
  "grade.term": "Termin",
  "grade.type": "Typ przedmiotu",
  "grade.type.p": "Obowiązkowy",
  "grade.type.r": "Różnice programowe",
  "grade.type.e": "Obieralny",
  "grade.length": "Liczba godzin",
  "grade.ects": "ECTS",
  "grade.finalGrade": "Ocena końcowa",
  "grade.finalGrade.empty": "Brak oceny końcowej",
  "grade.seePartials": "Zobacz oceny cząstkowe",
  "grade.partials": "Oceny cząstkowe",

  "gradePage.accumulatedEcts": "Zebrane punkty ECTS",
  "gradePage.avgPerYear": "Średnia ważona za rok",
  "gradePage.avgPerSemester": "Średnia ważona za semestr",
  "gradePage.summary": "Podsumowanie",
  "gradePage.subjects": "Przedmioty",
};
