export const strings = {
  "intl.switch.english": "Switch to english 🇬🇧",
  "intl.switch.polish": "Przełącz na język polski 🇵🇱",

  "virtual-university": "Wirtualny Dziekanat",
  student: "Student",
  teacher: "Dydaktyk",
  login: "Logowanie",
  "login.id": "Nr indeksu",
  "login.password": "Hasło",
  "login.logIn": "Zaloguj",
  "login.forgot": "Zapomniałem hasła",
  "login.email": "Adres e-mail",
  "login.recovery.btn": "Kontynuuj",
  "login.recovery": "Odzyskiwanie hasła",
  "login.recovery.success":
    "Na Twój e-mail zostały wysłane instrukcje resetu hasła",
  back: "Wróć",

  "login.button": "Zaloguj",

  "grade.grade": "Ocena",
  "grade.teacher": "Prowadzący",
  "grade.lessonType": "Forma zajęć",
  "grade.lessonType.aud": "Ćwiczenia audytoryjne",
  "grade.lessonType.labs": "Ćwiczenia laboratoryjne",
  "grade.lessonType.proj": "Ćwiczenia projektowe",
  "grade.lessonType.lectures": "Wykład",
  "grade.group": "Grupa",
  "grade.term": "Termin",
  "grade.type": "Typ przedmiotu",
  "grade.type.p": "Obowiązkowy",
  "grade.type.r": "Różnice programowe",
  "grade.type.e": "Obieralny",
  "grade.type.d": "Dodatkowy",
  "grade.type.pp": "Powtarzanie przedmiotu",
  "grade.type.i": "ITS",
  "grade.length": "Liczba godzin",
  "grade.ects": "ECTS",
  "grade.finalGrade": "Ocena końcowa",
  "grade.finalGrade.empty": "Brak oceny końcowej",
  "grade.seePartials": "Zobacz oceny cząstkowe",
  "grade.partials": "Oceny cząstkowe",
  "grade.partials.empty": "Brak ocen cząstkowych",

  "gradePage.accumulatedEcts": "Zebrane punkty ECTS",
  "gradePage.avgPerYear": "Średnia ważona za rok",
  "gradePage.avgPerSemester": "Średnia ważona za semestr",
  "gradePage.summary": "Podsumowanie",
  "gradePage.subjects": "Przedmioty",

  "nav.university": "Twoje studia",
  "nav.calendar": "Kalendarz",
  "nav.profile": "Profil",
  "nav.logout": "Wyloguj",
  "nav.news": "Ogłoszenia",
  "nav.contact": "Kontakt",
  "nav.university.grades": "Przedmioty",

  "contact.deansOffice": "Dziekanat",
  "contact.deansOffice.description":
    "Elektrotechniki, Automatyki, Informatyki i Inżynierii Biomedycznej Stacjonarne",
  "contact.support": "Osługa techniczna",
  "contact.support.description":
    "Zastrzeżenia działania wirtualnego dziekanatu",

  "see.news": "Zobacz więcej aktualności",
  "see.deansOffice": "Przejdź to strony dziekanatu",
  "see.vu": "Przejdź do strony CRI",
  change: "Zmień",
  "change.password": "Zmień hasło",

  "news.noNeews": "Brak nowych ogłoszeń",

  "calendar.see": "Zobacz kalendarz",

  "profile.personalData": "Dane osobowe",
  "profile.financialData": "Dane finansowe",
  "profile.loginData": "Dane logowania",
  "profile.agreements": "Zgody",
  "profile.id": "Nr indeksu",
  "profile.phone": "Telefon",
  "profile.email": "Email",
  "profile.address": "Adres stały",
  "profile.postAddress": "Adres do korespondencji",
  "profile.bornPlace": "Miejsce urodzenia",
  "profile.bornTime": "Data urodzenia",
  "profile.motherName": "Imię matki",
  "profile.fatherName": "Imię ojca",
  "profile.pesel": "PESEL",
  "profile.nationalId": "Dokument tożsamości",
  "profile.accountNumber": "Nr konta",
  "profile.agreement.email": "Zgoda na udostępnianie adresu e-mail",
  "profile.agreement.parents": "Zgoda na informowanie rodziców",
  "profile.info":
    "Student zobowiązany jest niezwłocznie powiadomić Dziekana Wydziału o wszelkich zmianach dotyczących stanu cywilnego, nazwiska lub adresu i o zmianie warunków materialnych, jeżeli wpływają one na przyznanie i wysokość pomocy materialnej",
};
